name: CI/CD Pipeline for Chatbot

on:
  push:
    branches:
      - '**'  # Trigger on all branches
  pull_request:
    branches:
      - master  # Trigger on PRs targeting master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests with Maven
        run: |
          cd ChatbotApplication
          mvn clean verify

  release-artifact:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'  # Trigger on push to master only

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR with Maven
        run: |
          cd ChatbotApplication
          mvn clean package

      - name: Create a Git tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Creating a tag based on timestamp (you can adjust this)
          git tag $TAG_NAME
          git remote set-url origin https://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@github.com/${{ github.repository }}.git
          git push origin $TAG_NAME  # Push the tag to GitHub

      - name: Upload JAR to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ChatbotApplication/target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
